baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Papelaria Galileu"
theme = "hugo-creative-theme"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Papelaria Galileu"
	description = "Papelaria Galileu, materiais de escritório, materiais de informática, serviços, Santa Bárbara d'Oeste, São Paulo"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Papelaria Galileu"

		[params.navigation.links]
			about     = "Sobre"
			services  = "Serviços"
			portfolio = "Localização"
			contact   = "Contato"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Papelaria Galileu"
		subtitle   = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis nesciunt consequatur ut nihil voluptatem fugiat eos eveniet alias in veniam?"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Nós temos o que você precisa!"
		description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
		buttonText  = "Venha nos visitar!"

	# Service section
	[params.services]
		headline = "Serviços feitos com qualidade incrível"

        [[params.services.list]]
            icon = "fa-clone"
            title = "Fotocópia"
            description = "Em vários formatos"

        [[params.services.list]]
			icon = "fa-paperclip"
			title = "Materiais de escritório"
			description = "Da melhor qualidade"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Currículo Vitae"
            description = ""

        [[params.services.list]]
            icon = "fa-credit-card"
            title = "Aceitamos cartão de crédito"
            description = "VISA, Mastercard, Hipercard"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Entre em contato conosco"
		description = "E receba o atendimento da melhor papelaria de Santa Bárbara d'Oeste"
		phone = "(19) 3463 6622 ou (19) 3455 3727"
		email = "vendasgalileu@gmail.com"
        facebook = "papelariagalileu"
